'use client';

import { useState, useEffect, type ElementType } from 'react';
import { Bot, FileText, Loader2, Sparkles, Wand2 } from 'lucide-react';
import { testPromptAction } from '@/app/quiz/actions';
import { type OptimizeLLMPerformanceOutput } from '@/ai/flows/optimize-llm-performance-with-system-prompt';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/hooks/use-toast';
import { Skeleton } from '@/components/ui/skeleton';

function Icon({ as, ...props }: { as: ElementType, [key: string]: any }) {
  const [isMounted, setIsMounted] = useState(false);
  const IconComponent = as;
  
  useEffect(() => {
    setIsMounted(true);
  }, []);

  if (!isMounted) {
    const size = props.size || 24;
    const width = props.width || size;
    const height = props.height || size;
    return <div style={{ width, height }} />;
  }

  return <IconComponent {...props} />;
}

export function PromptTesterClient() {
  const [question, setQuestion] = useState('Which planet is known as the Red Planet?');
  const [context, setContext] = useState('Mars is often called the Red Planet because of its reddish appearance.');
  const [isLoading, setIsLoading] = useState(false);
  const [result, setResult] = useState<OptimizeLLMPerformanceOutput | null>(null);
  const { toast } = useToast();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!question) {
        toast({title: "Question missing", description: "Please provide a question to test.", variant: "destructive"})
        return;
    }
    setIsLoading(true);
    setResult(null);
    try {
      const response = await testPromptAction({ question, context });
      setResult(response);
    } catch (error) {
      toast({ title: 'Error', description: 'Failed to get a response from the AI.', variant: 'destructive' });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="grid md:grid-cols-2 gap-6 items-start">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2"><Icon as={Wand2} /> Prompt Input</CardTitle>
          <CardDescription>Enter a question and optional context to test the AI's response.</CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="question" className="flex items-center gap-2"><Icon as={Sparkles} size={16} /> Question</Label>
              <Textarea
                id="question"
                placeholder="Enter the question here"
                value={question}
                onChange={(e) => setQuestion(e.target.value)}
                rows={4}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="context" className="flex items-center gap-2"><Icon as={FileText} size={16} /> Context (Optional)</Label>
              <Textarea
                id="context"
                placeholder="Provide any context, data, or documents"
                value={context}
                onChange={(e) => setContext(e.target.value)}
                rows={8}
              />
            </div>
            <Button type="submit" disabled={isLoading} className="w-full">
              {isLoading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Generating...
                </>
              ) : (
                'Generate Answer'
              )}
            </Button>
          </form>
        </CardContent>
      </Card>
      <Card className="min-h-[400px]">
        <CardHeader>
          <CardTitle className="flex items-center gap-2"><Icon as={Bot} /> AI Output</CardTitle>
          <CardDescription>The answer and reasoning generated by the AI model.</CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading && (
            <div className="space-y-4">
                <Skeleton className="h-6 w-1/4" />
                <Skeleton className="h-4 w-3/4" />
                <div className="pt-4 space-y-2">
                    <Skeleton className="h-6 w-1/3" />
                    <Skeleton className="h-4 w-full" />
                    <Skeleton className="h-4 w-5/6" />
                </div>
            </div>
          )}
          {!isLoading && !result && (
            <div className="flex items-center justify-center h-40 text-muted-foreground">
              <p>AI response will appear here.</p>
            </div>
          )}
          {result && (
            <div className="space-y-6">
              <div>
                <h3 className="text-lg font-semibold text-primary mb-2">Answer</h3>
                <p className="text-foreground">{result.answer}</p>
              </div>
              {result.reasoning && (
                <div>
                  <h3 className="text-lg font-semibold text-primary mb-2">Reasoning</h3>
                  <p className="text-muted-foreground prose prose-sm max-w-none">{result.reasoning}</p>
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
